BEGIN TRANSACTION;
INSERT INTO "schnipsel_codes" VALUES (1,1,'11','trösch1','Procedure TForm1.CodeEntryClick(Sender: Tobject);\r\nvar i : integer;\r\n    s : string;\r\nbegin\r\n  s:=(Sender as TstaticText).name;  ökljölk öljölkj öjölkj öljölj ölölkj öl ölöl l ,mnb mn jjöjö öjöj \r\nöljöljölkj ölöljölj öljölkj öljölkj ölölj öljölj slkjsd sjöalksd saöjdöalkjsd saöjdölkj sdalkjdölj \r\nsöljdöljkas saöljdölkj saöljkdölkj\r\n  s:=copy(s,pos(s)+1,length(s));\r\n  i:=strtoint(s);\r\n\r\n   LangTypesList.visible:=false;\r\n   LTPanel.visible:=false;\r\n   Code_PageControl.visible:=true;\r\nend;\r\n1\r\n');
INSERT INTO "schnipsel_codes" VALUES (3,1,'2','andreas','Procedure TForm1.ShowTypeCodeList(Lang_id : integer);\r\nvar i,spacer       : integer;\r\n    TEntry,\r\n    CEntry         : Tstatictext;\r\n    Centry_line    : TdividerBevel;\r\n    Expand_Image   : TImage;\r\n    stra           : array of string;\r\nbegin\r\n CodesList.clear;\r\n TypesList.clear;\r\n LangTypesList.visible:=false;\r\n try                               ');
INSERT INTO "schnipsel_codes" VALUES (4,1,'23232323','bla bla','Id eins anderer Inhalt');
INSERT INTO "schnipsel_codes" VALUES (12,13,'1.5','A.Trösch','lkjnökljsöflkjsödlkjgöslkjd\r\ndfsgkäöskldgäöklsdfägkölsädfg\r\ndfsgäökdägköläösdklfg\r\n\r\n');
INSERT INTO "schnipsel_codes" VALUES (13,14,'1.1','Naha','sfffffffffff\r\nsfdsdf\r\nsadfasdf\r\nsdfasdf\r\nsdfasdf\r\n');
INSERT INTO "schnipsel_codes" VALUES (14,15,'2.2','Andereree','eraasfafasf\r\nsafsfasfasfasf\r\nsadfasfasfsafasf\r\nsdfasfasfsfdasf\r\nsfdasfsfasdf\r\n\r\n');
INSERT INTO "schnipsel_codes" VALUES (16,17,'12','AUTHOR','ölkölkölköl\r\n');
INSERT INTO "schnipsel_codes" VALUES (17,18,'VERSION','AUTHOR','eintrag 4\r\n\r\n');
INSERT INTO "schnipsel_codes" VALUES (22,4,'1.0','Author','version 1.0\r\n');
INSERT INTO "schnipsel_codes" VALUES (23,0,'','','');
INSERT INTO "schnipsel_comments" VALUES (1,2,0,'Andreas22','quatsch misch im schlaf voll22');
INSERT INTO "schnipsel_comments" VALUES (2,2,0,'Andreas Andreas','sprich mit meinem Arsch');
INSERT INTO "schnipsel_favorites" VALUES (4,1);
INSERT INTO "schnipsel_favorites" VALUES (5,3);
INSERT INTO "schnipsel_language" VALUES (1,'Javascript','JS');
INSERT INTO "schnipsel_language" VALUES (2,'Phyton','py');
INSERT INTO "schnipsel_language" VALUES (3,'Pascal','Pas');
INSERT INTO "schnipsel_language" VALUES (4,'PHP','PHP');
INSERT INTO "schnipsel_language" VALUES (6,'Shell','SH');
INSERT INTO "schnipsel_language" VALUES (8,'Lua','Lua');
INSERT INTO "schnipsel_language" VALUES (9,'cobolss','cobss');
INSERT INTO "schnipsel_language" VALUES (10,'Object','obj');
INSERT INTO "schnipsel_language" VALUES (11,'basi','bas');
INSERT INTO "schnipsel_language" VALUES (14,'script','st');
INSERT INTO "schnipsel_language" VALUES (15,'batch','bat');
INSERT INTO "schnipsel_language" VALUES (16,'englisch','en');
INSERT INTO "schnipsel_language" VALUES (18,'Neuer Eintrag','NE');
INSERT INTO "schnipsel_language" VALUES (19,'Javascript','Java');
INSERT INTO "schnipsel_links" VALUES (1,1,'google1.de','http://google1.de');
INSERT INTO "schnipsel_links" VALUES (2,1,'web.de','http://web.de');
INSERT INTO "schnipsel_links" VALUES (4,1,'linktest','http://linktest.com');
INSERT INTO "schnipsel_links" VALUES (6,1,'testeintrag2','http://testeintrag2.de');
INSERT INTO "schnipsel_names" VALUES (1,1,1,'TForm1 = class(TForm)1');
INSERT INTO "schnipsel_names" VALUES (3,1,2,'procedure CategorieListEditSelectionChange');
INSERT INTO "schnipsel_names" VALUES (4,1,2,'procedure CatMoveUpClick(Sender: TObject);   ');
INSERT INTO "schnipsel_names" VALUES (13,6,1,'Neuer Neuer Eintrag');
INSERT INTO "schnipsel_names" VALUES (14,6,1,'Linux New');
INSERT INTO "schnipsel_names" VALUES (15,8,2,'testtestttest');
INSERT INTO "schnipsel_names" VALUES (17,1,1,'ll');
INSERT INTO "schnipsel_names" VALUES (18,6,2,'testeditor');
INSERT INTO "schnipsel_required" VALUES (22,2,0,'lkjhlkhlk','zeile1\r\nzeile2','ljlkj');
INSERT INTO "schnipsel_required" VALUES (23,2,1,'asdasd','zeile 1 zeile 1 zeile 1 zeile 1 zeile 1 zeile 1 zeile 1 zeile 1 zeile 1 zeile 1','vbcvb');
INSERT INTO "schnipsel_required" VALUES (24,2,0,'asdasd','zeile 1 zeile 1 zeile 1 zeile 1 zeile 1 zeile 1 zeile 1 zeile 1 zeile 1 zeile 1 zeile 1 zeile 1 zeile 1 zeile 1 zeile 1 zeile 1 zeile 1 zeile 1 zeile 1 zeile 1','vbcvb');
INSERT INTO "schnipsel_required" VALUES (25,2,3,'linkauf 3','link auf 3','sfsfsf');
INSERT INTO "schnipsel_required" VALUES (26,2,0,'test','testhint','testurl');
INSERT INTO "schnipsel_required" VALUES (28,2,0,'rqneu2','reqdesc2','http://req2.de');
INSERT INTO "schnipsel_required" VALUES (29,2,0,'NeuNeuNeu','NeuNeuNeudesc','http://NeruNeuNeu.de');
INSERT INTO "schnipsel_required" VALUES (30,1,0,'unit','unit irgendwas','http://was.de');
INSERT INTO "schnipsel_required" VALUES (31,1,0,'Unit 2','unit2 unit 2','http://nochwas.de');
INSERT INTO "schnipsel_required" VALUES (32,1,1,'unit3','Unit3 new','http://was.de');
INSERT INTO "schnipsel_types" VALUES (1,'function');
INSERT INTO "schnipsel_types" VALUES (2,'procedure');
INSERT INTO "schnipsel_types" VALUES (3,'objekt');
COMMIT;
